export const BIBLE_BOOKS = [
  { name: "Genesis", abrv: "Gen", chapters: 50 },
  { name: "Exodus", abrv: "Exod", chapters: 40 },
  { name: "Leviticus", abrv: "Lev", chapters: 27 },
  { name: "Numbers", abrv: "Num", chapters: 36 },
  { name: "Deuteronomy", abrv: "Deut", chapters: 34 },
  { name: "Joshua", abrv: "Josh", chapters: 24 },
  { name: "Judges", abrv: "Judg", chapters: 21 },
  { name: "Ruth", abrv: "Ruth", chapters: 4 },
  { name: "1 Samuel", abrv: "1Sam", chapters: 31 },
  { name: "2 Samuel", abrv: "2Sam", chapters: 24 },
  { name: "1 Kings", abrv: "1Kgs", chapters: 22 },
  { name: "2 Kings", abrv: "2Kgs", chapters: 25 },
  { name: "1 Chronicles", abrv: "1Chr", chapters: 29 },
  { name: "2 Chronicles", abrv: "2Chr", chapters: 36 },
  { name: "Ezra", abrv: "Ezra", chapters: 10 },
  { name: "Nehemiah", abrv: "Neh", chapters: 13 },
  { name: "Esther", abrv: "Esth", chapters: 13 },
  { name: "Job", abrv: "Job", chapters: 42 },
  { name: "Psalms", abrv: "Ps", chapters: 150 },
  { name: "Proverbs", abrv: "Prov", chapters: 31 },
  { name: "Ecclesiastes", abrv: "Eccl", chapters: 12 },
  { name: "Song of Solomon", abrv: "Song", chapters: 8 },
  { name: "Isaiah", abrv: "Isa", chapters: 66 },
  { name: "Jeremiah", abrv: "Jer", chapters: 52 },
  { name: "Lamentations", abrv: "Lam", chapters: 5 },
  { name: "Ezekiel", abrv: "Ezek", chapters: 48 },
  { name: "Daniel", abrv: "Dan", chapters: 12 },
  { name: "Hosea", abrv: "Hos", chapters: 14 },
  { name: "Joel", abrv: "Joel", chapters: 3 },
  { name: "Amos", abrv: "Amos", chapters: 9 },
  { name: "Obadiah", abrv: "Obad", chapters: 1 },
  { name: "Jonah", abrv: "Jonah", chapters: 4 },
  { name: "Micah", abrv: "Mic", chapters: 4 },
  { name: "Nahum", abrv: "Nah", chapters: 3 },
  { name: "Habakkuk", abrv: "Hab", chapters: 3 },
  { name: "Zephaniah", abrv: "Zeph", chapters: 3 },
  { name: "Haggai", abrv: "Hag", chapters: 2 },
  { name: "Zechariah", abrv: "Zech", chapters: 14 },
  { name: "Malachi", abrv: "Mal", chapters: 4 },
  { name: "Matthew", abrv: "Matt", chapters: 28 },
  { name: "Mark", abrv: "Mark", chapters: 16 },
  { name: "Luke", abrv: "Luke", chapters: 24 },
  { name: "John", abrv: "John", chapters: 21 },
  { name: "Acts", abrv: "Acts", chapters: 28 },
  { name: "Romans", abrv: "Rom", chapters: 16 },
  { name: "1 Corinthians", abrv: "1Cor", chapters: 16 },
  { name: "2 Corinthians", abrv: "2Cor", chapters: 13 },
  { name: "Galatians", abrv: "Gal", chapters: 6 },
  { name: "Ephesians", abrv: "Eph", chapters: 6 },
  { name: "Philippians", abrv: "Phil", chapters: 4 },
  { name: "Colossians", abrv: "Col", chapters: 4 },
  { name: "1 Thessalonians", abrv: "1Thess", chapters: 5 },
  { name: "2 Thessalonians", abrv: "2Thess", chapters: 3 },
  { name: "1 Timothy", abrv: "1Tim", chapters: 6 },
  { name: "2 Timothy", abrv: "2Tim", chapters: 4 },
  { name: "Titus", abrv: "Titus", chapters: 3 },
  { name: "Philemon", abrv: "Phlm", chapters: 1 },
  { name: "Hebrews", abrv: "Heb", chapters: 13 },
  { name: "James", abrv: "Jas", chapters: 5 },
  { name: "1 Peter", abrv: "1Pet", chapters: 5 },
  { name: "2 Peter", abrv: "2Pet", chapters: 3 },
  { name: "1 John", abrv: "1John", chapters: 5 },
  { name: "2 John", abrv: "2John", chapters: 1 },
  { name: "3 John", abrv: "3John", chapters: 1 },
  { name: "Jude", abrv: "Jude", chapters: 1 },
  { name: "Revelation", abrv: "Rev", chapters: 22 }
]


export const BIBLE_VERSIONS = [
  { version: "King James Version (KJV)", url: "https://ebible.org/Scriptures/eng-kjv_vpl.zip", id: "eng-kjv" },
  { version: "American Standard Version (ASV)", url: "https://ebible.org/Scriptures/eng-asv_vpl.zip", id: "eng-asv"}
]
