export const BIBLE_BOOKS = [
  { name: "Genesis", abrv: "GEN", chapters: 50 },
  { name: "Exodus", abrv: "EXO", chapters: 40 },
  { name: "Leviticus", abrv: "LEV", chapters: 27 },
  { name: "Numbers", abrv: "NUM", chapters: 36 },
  { name: "Deuteronomy", abrv: "DEU", chapters: 34 },
  { name: "Joshua", abrv: "JOS", chapters: 24 },
  { name: "Judges", abrv: "JDG", chapters: 21 },
  { name: "Ruth", abrv: "RUT", chapters: 4 },
  { name: "1 Samuel", abrv: "1SA", chapters: 31 },
  { name: "2 Samuel", abrv: "2SA", chapters: 24 },
  { name: "1 Kings", abrv: "1KI", chapters: 22 },
  { name: "2 Kings", abrv: "2KI", chapters: 25 },
  { name: "1 Chronicles", abrv: "1CH", chapters: 29 },
  { name: "2 Chronicles", abrv: "2CH", chapters: 36 },
  { name: "Ezra", abrv: "EZR", chapters: 10 },
  { name: "Nehemiah", abrv: "NEH", chapters: 13 },
  { name: "Esther", abrv: "EST", chapters: 13 },
  { name: "Job", abrv: "JOB", chapters: 42 },
  { name: "Psalms", abrv: "PSA", chapters: 150 },
  { name: "Proverbs", abrv: "PRO", chapters: 31 },
  { name: "Ecclesiastes", abrv: "ECC", chapters: 12 },
  { name: "Song of Solomon", abrv: "SNG", chapters: 8 },
  { name: "Isaiah", abrv: "ISA", chapters: 66 },
  { name: "Jeremiah", abrv: "JER", chapters: 52 },
  { name: "Lamentations", abrv: "LAM", chapters: 5 },
  { name: "Ezekiel", abrv: "EZK", chapters: 48 },
  { name: "Daniel", abrv: "DAN", chapters: 12 },
  { name: "Hosea", abrv: "HOS", chapters: 14 },
  { name: "Joel", abrv: "JOL", chapters: 3 },
  { name: "Amos", abrv: "AMO", chapters: 9 },
  { name: "Obadiah", abrv: "OBA", chapters: 1 },
  { name: "Jonah", abrv: "JON", chapters: 4 },
  { name: "Micah", abrv: "MIC", chapters: 4 },
  { name: "Nahum", abrv: "NAM", chapters: 3 },
  { name: "Habakkuk", abrv: "HAB", chapters: 3 },
  { name: "Zephaniah", abrv: "ZEP", chapters: 3 },
  { name: "Haggai", abrv: "HAG", chapters: 2 },
  { name: "Zechariah", abrv: "ZEC", chapters: 14 },
  { name: "Malachi", abrv: "MAL", chapters: 4 },
  { name: "Matthew", abrv: "MAT", chapters: 28 },
  { name: "Mark", abrv: "MRK", chapters: 16 },
  { name: "Luke", abrv: "LUK", chapters: 24 },
  { name: "John", abrv: "JHN", chapters: 21 },
  { name: "Acts", abrv: "ACT", chapters: 28 },
  { name: "Romans", abrv: "ROM", chapters: 16 },
  { name: "1 Corinthians", abrv: "1CO", chapters: 16 },
  { name: "2 Corinthians", abrv: "2CO", chapters: 13 },
  { name: "Galatians", abrv: "GAL", chapters: 6 },
  { name: "Ephesians", abrv: "EPH", chapters: 6 },
  { name: "Philippians", abrv: "PHP", chapters: 4 },
  { name: "Colossians", abrv: "COL", chapters: 4 },
  { name: "1 Thessalonians", abrv: "1TH", chapters: 5 },
  { name: "2 Thessalonians", abrv: "2TH", chapters: 3 },
  { name: "1 Timothy", abrv: "1TI", chapters: 6 },
  { name: "2 Timothy", abrv: "2TI", chapters: 4 },
  { name: "Titus", abrv: "TIT", chapters: 3 },
  { name: "Philemon", abrv: "PHM", chapters: 1 },
  { name: "Hebrews", abrv: "HEB", chapters: 13 },
  { name: "James", abrv: "JAS", chapters: 5 },
  { name: "1 Peter", abrv: "1PE", chapters: 5 },
  { name: "2 Peter", abrv: "2PE", chapters: 3 },
  { name: "1 John", abrv: "1JN", chapters: 5 },
  { name: "2 John", abrv: "2JN", chapters: 1 },
  { name: "3 John", abrv: "3JN", chapters: 1 },
  { name: "Jude", abrv: "JUD", chapters: 1 },
  { name: "Revelation", abrv: "REV", chapters: 22 }
]


export interface BibleVersion {
  version: string,
  url: string,
  id: string
}

export const BIBLE_VERSIONS: Array<BibleVersion> = [
  { version: "King James Version (KJV)", url: "https://ebible.org/Scriptures/eng-kjv_vpl.zip", id: "eng-kjv" },
  { version: "American Standard Version (ASV)", url: "https://ebible.org/Scriptures/eng-asv_vpl.zip", id: "eng-asv" },
  { version: "Bible in Basic English (BBE)", url: "https://ebible.org/Scriptures/engBBE_vpl.zip", id: "engBBE" },
  { version: "Plain English Version", url: "https://ebible.org/Scriptures/engPEV_vpl.zip", id: "engPEV" }
]
