//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "authors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub display_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authors_songs::Entity")]
    AuthorsSongs,
}

impl Related<super::authors_songs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorsSongs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
