//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bible")]
pub struct Model {
    #[sea_orm(column_name = "verseID", primary_key, auto_increment = false)]
    pub verse_id: String,
    pub canon_order: String,
    pub book: String,
    pub chapter: String,
    #[sea_orm(column_name = "startVerse")]
    pub start_verse: String,
    #[sea_orm(column_name = "endVerse")]
    pub end_verse: String,
    #[sea_orm(
        column_name = "verseText",
        column_type = "Binary(BlobSize::Blob(None))"
    )]
    pub verse_text: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
