//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::default_template::Entity as DefaultTemplate;
pub use super::template::Entity as Template;
pub use super::video_thumbnail::Entity as VideoThumbnail;
